[package]
name = "shl-service-cache"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
shl-service-cache-macro = { path = "../shl-service-cache-macro", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rustis = "0.13.3"
thiserror = "2.0.12"

[features]
macro = ["dep:shl-service-cache-macro"]