[workspace]
members = [
    "shl-observability",
    "shl-redis-cache-macro",
    "shl-redis-cache-service",
    "shl-service-cache",
    "shl-service-cache-macro",
    "shl-sqlx",
]
resolver = "3"

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
cfg-if = "1"
