[workspace]
members = ["shl-service-cache", "shl-service-cache-macro", "shl-sqlx", "shl-observability", "shl-redis-cache-service", "shl-redis-cache-macro"]
resolver = "3"

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
cfg-if = "1"
