[package]
name = "ntex-error-macro"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
ntex = "2"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[lib]
proc-macro = true
